grade_type_index:
    path:     /
    defaults: { _controller: "AppBundle:TypeGrade:index" }
    methods:  GET

grade_type_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:TypeGrade:show" }
    methods:  GET

grade_type_new:
    path:     /new
    defaults: { _controller: "AppBundle:TypeGrade:new" }
    methods:  [GET, POST]

grade_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:TypeGrade:edit" }
    methods:  [GET, POST]

grade_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:TypeGrade:delete" }
    methods:  DELETE
